version: '3'

services:
  backend:
    build:
      context: ./django-mysql-api/Proyecto_API
    command: gunicorn Proyecto_API.wsgi --bind 0.0.0.0:8000
    ports: 
     - 8000:8000
  frontend:
    build:
      context: ./react-crud-companies
    volumes:
      - react_build:/react-crud-companies/build
  nginx:
    image: nginx:latest
    ports: 
      - 80:8080
    volumes:
      - ./nginx/nginx-setup.conf:/etc/nginx/conf.d/default.conf:ro
      - react_build:/var/www/react-crud-companies
    depends_on:
      - backend
      - frontend
volumes:
  react_build:
